services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  hasura:
    image: hasura/graphql-engine:v2.40.0
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/recipes
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: aklile1996
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "this_is_a_very_long_secret_key_12345"}'

  go-backend:
    build:
      context: ./backend         # ✅ This points to your Go backend folder
    restart: always
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/recipes
      HASURA_GRAPHQL_ENDPOINT: http://hasura:8080/v1/graphql

volumes:
  postgres_data:
